export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"


export const SAVE_ACCOUNT = "SAVE_ACCOUNT"
export const POST_COMMENT = "POST_COMMENT";
export const ADD_ACCOUNTS = "ADD_ACCOUNTS";
export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const ACCOUNTS_LOAD_FAILED = "ACCOUNTS_LOAD_FAILED"; 